name: hot_reload
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  get: ^4.6.5
  flutter_spinkit: ^5.2.0
  #  animated_splash_screen: ^1.3.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

  # services
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  image_picker: ^1.0.2
  url_launcher: ^6.1.11
  iconsax: ^0.0.8
  firebase_core: ^2.24.2
  font_awesome_flutter: ^10.4.0
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0
  dotted_border: ^2.1.0
  readmore: ^2.2.0
  intl_phone_number_input: ^0.7.0+2
  shimmer: ^2.0.0
  file_picker: ^4.5.1
  google_fonts: ^4.0.4
  flutter_svg: ^1.1.6
  table_calendar: ^3.0.9
  intl: ^0.18.1

  ## location
  google_maps_flutter: ^2.3.0
  geolocator: ^10.1.0
  location: ^5.0.3
  flutter_dotenv: ^5.0.3

  ## check connection
  connectivity_plus: 5.0.2
  shared_preferences: ^2.2.0
  liquid_pull_to_refresh: ^3.0.1

  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0
  cached_network_image: ^3.2.3
  flutter_config: ^2.0.2
  mobile_scanner: ^2.1.0
  pretty_qr_code: ^3.3.0
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^5.0.11
#  awesome_notifications: ^0.6.19
  firebase_messaging: ^14.7.10
  http: ^0.13.5
  emailjs: ^1.1.0
  payhere_mobilesdk_flutter: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/brands_logo/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/brands_logo/app_icon.png"
  remove_alpha_ios: true


flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  image: "assets/images/brands_logo/native_icon.png"
  color_dark: "#121212"
  fullscreen: true

  #  flutter pub run flutter_native_splash:create
  #  flutter pub run flutter_launcher_icons:main

  #https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/animations/
    - assets/nav_icons/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/images/brands_logo/
    - assets/images/page_images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

